### ISSUE TITLE
Changing color of the text and Title not working!

### ISSUE THREAD

**Issue by rakhtsavelives** [amlcurran/ShowcaseView#350] opened 2015-12-28 11:02 UTC
new ShowcaseView.Builder(getActivity())
                .withNewStyleShowcase()
                .singleShot(1)
                .setTarget(new ViewTarget(fabEmergency))
                .setContentTitlePaint(new TextPaint(colorTitle))
                .setContentTextPaint(new TextPaint(colorText))
                .setContentTitle("Title")
                .setContentText("Text")
                .build();

**Comment by amlcurran** [comment] 2016-02-10 20:29
Closing this, as I think it is a duplicate of #361

**Closed** 2016-02-10 20:29 UTC
Labels: duplicate

**Comment by amlcurran** [comment] 2016-02-10 20:31
as an aside, the constructor for `TextPaint` does not take a color, it takes a set of flags: http://developer.android.com/reference/android/text/TextPaint.html#TextPaint(int)
